- .github/workflows/ci.yml
- CHANGELOG.md
- Cargo.toml
- README.md
- tabulon/src/floatfuncs.rs
By the time this is released, this won't be the most recent version and it'll let us switch to 2024 edition.
> Use Rust 1.85 as the MSRV

- .github/workflows/ci.yml
This has a change to only run `no_std` checks on the libraries since examples and such aren't likely to be `no_std`, nor do they need to be.
> Run clippy against min-ver targets.

- examples/vello_viewer/src/main.rs
- tabulon/src/graphics_bag.rs
This also restructures things so the DXF file is loaded once, so that the graphics bag is constructed once, and so that transforms don't cause everything to be recomputed.
It also enables a more interactive present mode, which improves responsiveness.
> vello_viewer: Add basic panning and zooming with primary cursor.

- tabulon/src/shape.rs
- tabulon_dxf/src/lib.rs
Angles in dxf-rs are in degrees, but angles in Kurbo are in radians, and the start and end angles are used instead of sweep angles. These are now correctly calculated for Kurbo use.
Correctly translating the angles dramatically improves performance because Arcs are now 360 times shorter, thus generate fewer segments.
`Arc` is moved to the set of shapes that are converted to paths before being transformed, because I was getting incorrect results from `Affine` multiplication with `kurbo::Arc`.
> tabulon_dxf: Correct Arc translation.

- tabulon_dxf/src/lib.rs
Supporting TEXT/MTEXT/DTEXT formatting properly will require range styled text, and will require a real parser.
This change simply implements the special character escapes (this is all of them), and suppresses some more common formatting commands.
> tabulon_dxf: Support character escapes and suppress text formatting.

- tabulon_dxf/src/lib.rs
It seems that both `rotation_angle` and `x_axis_direction` are used, but are mutually exclusive, so it is safe to add them together.
> tabulon_dxf: use MTEXT `x_axis_direction`.

- tabulon_dxf/src/lib.rs
- tabulon_vello/src/lib.rs
MTEXT derives its default inline alignment from the attachment point, so I've added that.
Previously I was interpreting `reference_rectangle_width` as the reflow width of the MTEXT, it turns out that this is a cached parameter like `vertical_height`.
`column_width` is the correct reflow width for MTEXTs.
> tabulon_dxf: Derive MTEXT alignment from attachment point.

- examples/vello_simple/src/main.rs
- examples/vello_viewer/src/main.rs
- tabulon/src/graphics_bag.rs
- tabulon/src/lib.rs
- tabulon/src/shape.rs
- tabulon/src/text.rs
- tabulon_dxf/src/lib.rs
- tabulon_vello/src/lib.rs
Managed transforms have a four byte `TransformHandle` which is a lot more space efficient than an `Affine` on each item.
tabulon_dxf: Expose entity handles for lines.
vello_viewer: Debug print the `Entity` that was picked, rather than the shape that was picked, this is a step toward surfacing more interesting information to display on screen.
> Introduce managed transforms on `GraphicsBag`.

- tabulon/src/lib.rs
Instead of having `std` in scope, require bringing it into scope explicitly.
Other crates remain the same as they are now.
> tabulon: Be more `no_std`

- .github/workflows/ci.yml
This separates the `no_std` check to use a separate variable as `vello` does now. Also, check `no_std` on stable wasm clippy, and check more targets for the MSRV now that it is separate from `no_std`.
> ci: Check more for MSRV, no_std

- tabulon_dxf/src/lib.rs
In order to handle shapes not in the default orientation (+Z) we need support for some basic 3D transforms; currently there is no convenient way to do the transforms we need, so disable these shapes.
> tabulon_dxf: Disable drawing off-axis shapes for now.

- tabulon/src/graphics_bag.rs
- tabulon/src/render_layer.rs
- tabulon_dxf/src/lib.rs
`usize` is unnecessary, and opaque handles are better for this use.
> Use `ItemHandle` for `GraphicsItem`s in `GraphicsBag`.

- examples/vello_simple/src/main.rs
- examples/vello_viewer/src/main.rs
- tabulon/src/graphics_bag.rs
- tabulon/src/shape.rs
- tabulon_vello/src/lib.rs
It is common for many items to share a single `FatPaint`, so we should
store them in a palette.
This also further reduces the size of each `GraphicsItem`.
> Put `FatPaint`s in a palette, addressed with `PaintHandle`.

- .github/workflows/ci.yml
- Cargo.lock
- Cargo.toml
- examples/vello_viewer/Cargo.toml
- examples/vello_viewer/src/main.rs
This can be used by building `vello_viewer` with the `tracing-tracy` feature and then running the tracy client and connecting it once the viewer is running.
> Add support for tracing and tracy

- tabulon/src/lib.rs
The empty line is needed so that `cargo doc` will see the link definition correctly.
> tabulon: Fix cargo doc warning about libm link

- examples/vello_viewer/src/main.rs
- tabulon/src/graphics_bag.rs
- tabulon/src/render_layer.rs
- tabulon/src/shape.rs
- tabulon_dxf/src/lib.rs
View culling pass can not currently cull text items because there is no facility to measure them.
Measuring text items will involve moving a font context into tabulon.
> tabulon_dxf: Render entities to individual items, and do basic culling.

- examples/vello_viewer/src/main.rs
- tabulon/src/shape.rs
- tabulon_dxf/src/lib.rs
This allows larger drawings to be viewed at default scale, since most large drawings lean heavily on INSERTs.
vello_viewer: Because INSERTs often span large distances and include many lines, it was necessary to decompose items into `PathSeg`s for computing the AABB index used for culling and picking. 
This allows enclosing INSERTs to be culled for viewing, and not included in picking calculations when none of their lines are near the cursor.
The picking logic is also improved, and does about half as much work (due to only computing `nearest` once).
The AABB index's indexing precision is reduced to `f32`, which makes it more efficient in space and time.
> tabulon_dxf: Consolidate lines in INSERTs into `BezPath`s.

- examples/dxf_viewer/src/main.rs
- tabulon/src/text.rs
- tabulon_dxf/src/lib.rs
- tabulon_vello/src/lib.rs
tabulon: Add paint to `FatText`.
tabulon_vello: Render color paints from `FatText`
dxf_viewer: Light adapt all paints in drawing.
> tabulon_dxf: Attach color paints to text items.

- tabulon_vello/src/lib.rs
With very small font sizes, like WCS font sizes from DXF drawings, the font scaler quantizes coordinates aggressively which introduces artifacts. This hack increases the font size for scaling, and then reverses this with a glyph transform.
This has a slight performance hit.
> tabulon_vello: Introduce glyph scaling hack to fix very small text.

- examples/dxf_viewer/src/main.rs
I introduced this issue when transitioning to ui-events.
`PointerEvent::Leave` is triggered even during pointer capture, so should not end a pan.
> dxf_viewer: Don't end pan on `PointerEvent::Leave`.

- tabulon_dxf/src/lib.rs
Some files produce nonstandard negative values for line weight, which cause integer underflow when converting them to unsigned iotas.
> tabulon_dxf: Fix integer underflow in line weight conversion code.

- examples/dxf_viewer/src/main.rs
This prevents the default console from showing, which fixes an issue where the main thread blocks on console output, which is very slow on Windows.
> dxf_viewer: Use #[windows_subsystem = "windows"]
